controller_manager:
  ros__parameters:
    update_rate: 10 #Hz
    robotiq_85_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    robotiq_85_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

robotiq_85_forward_position_controller:
  ros__parameters:
    joints:
      - robotiq_85_left_knuckle_joint
    interface_name: position

    
