controller_manager:
  ros__parameters:
    update_rate: 10 #Hz
    robotiq_85_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    robotiq_85_forward_position_controller:
      type: position_controllers/GripperActionController

robotiq_85_forward_position_controller:
  ros__parameters:
    joint: robotiq_85_left_knuckle_joint #note how this is singular! Gripper can only deal w/ single DOF 
    state_interfaces:
    - position

    
